name: BlueUtils
version: 4.3-SNAPSHOT
main: de.blaumeise03.blueUtils.Plugin
api-version: 1.15
description: A library for Spigot plugins
load: STARTUP
author: Blaumeise03
website: blaumeise03.de

commands:
  blueUtils:
    permission: blueUtils.command
    description: Main-command with muliple uses

permissions:
  blueUtils.command:
    default: op
    description: Permission for the /blueUtils main-command
  blueUtils.command.reloadPlugin:
    default: op
    description: Permission for reloading plugins
  blueUtils.command.serverState:
    default: op
    description: Permission for getting and changing server states.
  blueUtils.command.resetStateTable:
    default: op
    description: Permission for droping and recreating the serverState-Table
  blueUtils.command.dumpSQLTimings:
    default: op
    description: Permission for dumping the SQL-Timings to a file
  blueUtils.thirdExecution:
    default: op
    description: Permission to execute a command for an other player
  blueUtils.command.*:
    default: op
    description: Wildcard-permission for all commands
    children:
      blueUtils.command: true
      blueUtils.command.reloadPlugin: true
      blueUtils.command.serverState: true
  blueUtils.*:
    default: op
    description: Wildcard
    children:
      blueUtils.thirdExecution: true
      blueUtils.command.*: true